theme: jekyll-theme-cayman
title: 
description: Simon Dold – PhD Student – University of Basel

# Optional: future pagination settings (already there)
plugins:
  - jekyll-paginate
paginate: 10
paginate_path: "/news/page:num/"
